// @letissier/design-system 0.2.0 · tokens.rs · sha256-0bc40e19be4234c1 · vendored by scripts/sync.mjs; change the design-system repo, not this copy
//! The LeTissier design tokens for Rust: colour roles per theme, sizes per
//! density, type, space, motion. See the design-system repo for what each is for.
//!
//! GENERATED by build/build.mjs from tokens/*.tokens.json — do not edit.
//! design-system 0.2.0 · change a token in tokens/, then run `npm run build`.
#![allow(dead_code)]

/// An sRGB colour with straight (unmultiplied) alpha.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Rgba {
    pub r: u8,
    pub g: u8,
    pub b: u8,
    pub a: u8,
}

impl Rgba {
    pub const fn rgb(r: u8, g: u8, b: u8) -> Self {
        Self { r, g, b, a: 255 }
    }
    pub const fn new(r: u8, g: u8, b: u8, a: u8) -> Self {
        Self { r, g, b, a }
    }
    /// `[r, g, b, a]` — e.g. for `egui::Color32::from_rgba_unmultiplied`.
    pub const fn to_array(self) -> [u8; 4] {
        [self.r, self.g, self.b, self.a]
    }
    /// `0xRRGGBB`, alpha dropped.
    pub const fn to_rgb_u32(self) -> u32 {
        ((self.r as u32) << 16) | ((self.g as u32) << 8) | self.b as u32
    }
}

/// A drop shadow, in logical pixels.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Shadow {
    pub offset_x: f32,
    pub offset_y: f32,
    pub blur: f32,
    pub spread: f32,
    pub color: Rgba,
}

/// A text style at one density. `size` is in logical pixels, `leading` a
/// multiple of the size, `tracking_em` a fraction of it.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TextStyle {
    pub family: &'static [&'static str],
    pub size: f32,
    pub weight: u16,
    pub leading: f32,
    pub tracking_em: f32,
    pub uppercase: bool,
}

/// The raw palette, by CIELAB lightness. Prefer the roles in [`color`].
pub mod palette {
    #[allow(unused_imports)]
    use super::*;
    pub mod neutral {
        #[allow(unused_imports)]
        use super::*;
        pub const TONE_0: Rgba = Rgba::rgb(0x00, 0x00, 0x00);
        /// LIGHT grey/950 — the canvas: stage, video, previz
        pub const TONE_5: Rgba = Rgba::rgb(0x10, 0x10, 0x12);
        /// LIGHT grey/900 — the dark ground
        pub const TONE_6: Rgba = Rgba::rgb(0x14, 0x14, 0x15);
        /// LIGHT grey/850
        pub const TONE_10: Rgba = Rgba::rgb(0x1c, 0x1c, 0x1e);
        /// LIGHT grey/800
        pub const TONE_13: Rgba = Rgba::rgb(0x21, 0x21, 0x24);
        /// LIGHT grey/750
        pub const TONE_17: Rgba = Rgba::rgb(0x2a, 0x2a, 0x2e);
        /// LIGHT grey/700
        pub const TONE_19: Rgba = Rgba::rgb(0x2e, 0x2e, 0x33);
        /// LIGHT grey/650
        pub const TONE_21: Rgba = Rgba::rgb(0x32, 0x32, 0x38);
        /// LIGHT grey/600
        pub const TONE_26: Rgba = Rgba::rgb(0x3c, 0x3c, 0x44);
        /// LIGHT grey/500
        pub const TONE_32: Rgba = Rgba::rgb(0x4a, 0x4a, 0x52);
        /// LIGHT grey/400
        pub const TONE_39: Rgba = Rgba::rgb(0x5c, 0x5c, 0x66);
        /// new — the one grey that draws a control's edge at 3:1 on both grounds
        pub const TONE_46: Rgba = Rgba::rgb(0x6d, 0x6c, 0x76);
        /// LIGHT grey/300
        pub const TONE_59: Rgba = Rgba::rgb(0x8c, 0x8c, 0x96);
        /// new — secondary text on a dark ground that still reads 5.7:1 on a hovered key
        pub const TONE_71: Rgba = Rgba::rgb(0xad, 0xad, 0xb7);
        /// LIGHT grey/250
        pub const TONE_79: Rgba = Rgba::rgb(0xc4, 0xc4, 0xcc);
        /// LIGHT grey/100 — primary text on dark
        pub const TONE_84: Rgba = Rgba::rgb(0xd2, 0xd2, 0xd8);
        /// LIGHT grey/200
        pub const TONE_86: Rgba = Rgba::rgb(0xd6, 0xd6, 0xdc);
        /// LIGHT grey/150
        pub const TONE_90: Rgba = Rgba::rgb(0xe2, 0xe2, 0xe7);
        /// LIGHT grey/75 — the light ground
        pub const TONE_94: Rgba = Rgba::rgb(0xec, 0xec, 0xef);
        /// LIGHT grey/50
        pub const TONE_97: Rgba = Rgba::rgb(0xf5, 0xf5, 0xf7);
        /// LIGHT grey/25
        pub const TONE_99: Rgba = Rgba::rgb(0xfb, 0xfb, 0xfc);
        pub const TONE_100: Rgba = Rgba::rgb(0xff, 0xff, 0xff);
    }
    pub mod cyan {
        #[allow(unused_imports)]
        use super::*;
        /// accent text, and the accent under the pointer, on a light ground
        pub const TONE_36: Rgba = Rgba::rgb(0x01, 0x5b, 0x7e);
        /// the accent on a light ground: 4.7:1 on the inset grey, 6:1 under white text
        pub const TONE_42: Rgba = Rgba::rgb(0x03, 0x6a, 0x91);
        /// LIGHT cyan/500 — the accent on a dark ground
        pub const TONE_74: Rgba = Rgba::rgb(0x39, 0xc2, 0xff);
        /// hover on a dark ground
        pub const TONE_80: Rgba = Rgba::rgb(0x78, 0xd1, 0xff);
    }
    pub mod amber {
        #[allow(unused_imports)]
        use super::*;
        /// warning text on a light ground: 4.6:1 even on a hovered raised control
        pub const TONE_39: Rgba = Rgba::rgb(0x80, 0x52, 0x00);
        /// warning text on a light ground until 0.1.1, when it moved to 39; no role uses it, and it stays because removing a token breaks whoever reads it
        pub const TONE_40: Rgba = Rgba::rgb(0x83, 0x55, 0x03);
        /// a warning fill on a light ground: still reads as amber, 3.1:1 on the light ground
        pub const TONE_56: Rgba = Rgba::rgb(0xb8, 0x79, 0x0b);
        /// LIGHT amber/400 — warn on a dark ground
        pub const TONE_78: Rgba = Rgba::rgb(0xff, 0xb3, 0x47);
    }
    pub mod red {
        #[allow(unused_imports)]
        use super::*;
        /// error text on a light ground: 4.6:1 even on a hovered raised control
        pub const TONE_39: Rgba = Rgba::rgb(0xbb, 0x01, 0x1e);
        /// an error fill on a light ground
        pub const TONE_40: Rgba = Rgba::rgb(0xbe, 0x09, 0x20);
        /// LIGHT red/500 — an error fill on a dark ground
        pub const TONE_59: Rgba = Rgba::rgb(0xff, 0x4d, 0x4d);
        /// error text on a dark ground: 5.1:1 on a raised control, where #ff4d4d is 4.4
        pub const TONE_64: Rgba = Rgba::rgb(0xfe, 0x6c, 0x67);
    }
    pub mod green {
        #[allow(unused_imports)]
        use super::*;
        /// ok text on a light ground: 4.6:1 even on a hovered raised control
        pub const TONE_39: Rgba = Rgba::rgb(0x00, 0x6a, 0x38);
        /// an ok fill on a light ground
        pub const TONE_40: Rgba = Rgba::rgb(0x02, 0x6d, 0x3a);
        /// ok on a dark ground — the same lightness as the dark amber and cyan, so no status outshouts another
        pub const TONE_76: Rgba = Rgba::rgb(0x33, 0xd6, 0x7e);
    }
    pub mod alpha {
        #[allow(unused_imports)]
        use super::*;
        pub const WHITE_6: Rgba = Rgba::new(0xff, 0xff, 0xff, 0x0f);
        pub const WHITE_10: Rgba = Rgba::new(0xff, 0xff, 0xff, 0x1a);
        pub const WHITE_16: Rgba = Rgba::new(0xff, 0xff, 0xff, 0x29);
        pub const BLACK_6: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x0f);
        pub const BLACK_10: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x1a);
        pub const BLACK_16: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x29);
        pub const BLACK_20: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x33);
        pub const BLACK_30: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x4d);
        pub const BLACK_40: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x66);
        pub const BLACK_45: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x73);
        pub const BLACK_55: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x8c);
        pub const CYAN_74_16: Rgba = Rgba::new(0x39, 0xc2, 0xff, 0x29);
        pub const CYAN_42_10: Rgba = Rgba::new(0x03, 0x6a, 0x91, 0x1a);
        pub const AMBER_78_14: Rgba = Rgba::new(0xff, 0xb3, 0x47, 0x24);
        pub const AMBER_56_16: Rgba = Rgba::new(0xb8, 0x79, 0x0b, 0x29);
        pub const RED_59_14: Rgba = Rgba::new(0xff, 0x4d, 0x4d, 0x24);
        pub const RED_40_10: Rgba = Rgba::new(0xbe, 0x09, 0x20, 0x1a);
        pub const GREEN_76_12: Rgba = Rgba::new(0x33, 0xd6, 0x7e, 0x1f);
        pub const GREEN_40_10: Rgba = Rgba::new(0x02, 0x6d, 0x3a, 0x1a);
    }
}

/// Colour roles, one module per theme.
pub mod color {
    #[allow(unused_imports)]
    use super::*;
    pub mod dark {
        #[allow(unused_imports)]
        use super::*;
        pub mod surface {
            #[allow(unused_imports)]
            use super::*;
            /// The app's background: the room everything else is in.
            pub const GROUND: Rgba = Rgba::rgb(0x14, 0x14, 0x15);
            /// A region set on the ground: a sidebar, an inspector, a card.
            pub const PANEL: Rgba = Rgba::rgb(0x1c, 0x1c, 0x1e);
            /// Set into a panel: a field, a track, a well, a list.
            pub const INSET: Rgba = Rgba::rgb(0x21, 0x21, 0x24);
            /// Anything you can press at rest: a button, a key, a chip that does something.
            pub const RAISED: Rgba = Rgba::rgb(0x2a, 0x2a, 0x2e);
            /// A raised control under the pointer.
            pub const RAISED_HOVER: Rgba = Rgba::rgb(0x32, 0x32, 0x38);
            /// Things that float above the page: menus, popovers, dialogs, toasts. Always with a line and an elevation.
            pub const OVERLAY: Rgba = Rgba::rgb(0x21, 0x21, 0x24);
            /// Where the work is shown: the stage, the video, the pixel map. Dark in both themes, because what is shown there is light.
            pub const CANVAS: Rgba = Rgba::rgb(0x10, 0x10, 0x12);
        }
        pub mod ink {
            #[allow(unused_imports)]
            use super::*;
            /// What the screen is about. Passes 4.5:1 on every surface.
            pub const PRIMARY: Rgba = Rgba::rgb(0xd2, 0xd2, 0xd8);
            /// Labels, supporting values, the text on a quiet button. Passes 4.5:1 on every surface.
            pub const SECONDARY: Rgba = Rgba::rgb(0xad, 0xad, 0xb7);
            /// Hints, units, timestamps, placeholders. Passes 4.5:1 on ground, panel, inset and overlay; not used on a raised control.
            pub const TERTIARY: Rgba = Rgba::rgb(0x8c, 0x8c, 0x96);
            /// Off: a control that cannot be used now, a source that is not sending. Never for content anyone has to read.
            pub const DISABLED: Rgba = Rgba::rgb(0x5c, 0x5c, 0x66);
            /// Text on an inverted chip or tooltip whose fill is ink/primary.
            pub const INVERSE: Rgba = Rgba::rgb(0x14, 0x14, 0x15);
            /// Text laid over the canvas — an overlay on video, a label on the stage. Light in both themes, as the canvas is dark in both.
            pub const ON_CANVAS: Rgba = Rgba::rgb(0xd2, 0xd2, 0xd8);
        }
        pub mod line {
            #[allow(unused_imports)]
            use super::*;
            /// A hairline between regions or rows. Decorative: it carries no meaning on its own.
            pub const SUBTLE: Rgba = Rgba::rgb(0x2e, 0x2e, 0x33);
            /// A firmer division, and the edge of anything that floats.
            pub const STRONG: Rgba = Rgba::rgb(0x3c, 0x3c, 0x44);
            /// The edge that says 'this is a field' — 3:1 against ground, panel and inset in both themes (WCAG 1.4.11). Separate from line/subtle so a quiet divider can never drag a control below the line.
            pub const CONTROL: Rgba = Rgba::rgb(0x6d, 0x6c, 0x76);
        }
        pub mod accent {
            #[allow(unused_imports)]
            use super::*;
            /// Fill of the primary action; the selection's edge; the focus ring.
            pub const DEFAULT: Rgba = Rgba::rgb(0x39, 0xc2, 0xff);
            /// The primary action under the pointer.
            pub const HOVER: Rgba = Rgba::rgb(0x78, 0xd1, 0xff);
            /// Text in the accent: a link, the selected tab's label. A step darker than the fill on a light ground, so it still reads on the selection wash.
            pub const INK: Rgba = Rgba::rgb(0x39, 0xc2, 0xff);
            /// Text and icons on an accent fill.
            pub const ON: Rgba = Rgba::rgb(0x10, 0x10, 0x12);
            /// The selection wash: a selected row, a drop target.
            pub const SOFT: Rgba = Rgba::new(0x39, 0xc2, 0xff, 0x29);
        }
        /// The keyboard focus ring: 2px, outside the control, on everything operable.
        pub const FOCUS: Rgba = Rgba::rgb(0x39, 0xc2, 0xff);
        pub mod ok {
            #[allow(unused_imports)]
            use super::*;
            /// A dot, a bar, a badge fill.
            pub const DEFAULT: Rgba = Rgba::rgb(0x33, 0xd6, 0x7e);
            /// Text that says it is fine.
            pub const INK: Rgba = Rgba::rgb(0x33, 0xd6, 0x7e);
            /// Text on an ok fill.
            pub const ON: Rgba = Rgba::rgb(0x10, 0x10, 0x12);
            /// The ground of an ok notice.
            pub const SOFT: Rgba = Rgba::new(0x33, 0xd6, 0x7e, 0x1f);
        }
        pub mod warn {
            #[allow(unused_imports)]
            use super::*;
            /// A dot, a bar, a badge fill.
            pub const DEFAULT: Rgba = Rgba::rgb(0xff, 0xb3, 0x47);
            /// Text that asks for attention.
            pub const INK: Rgba = Rgba::rgb(0xff, 0xb3, 0x47);
            /// Text on a warn fill — dark in both themes, because amber is a light colour.
            pub const ON: Rgba = Rgba::rgb(0x10, 0x10, 0x12);
            /// The ground of a warning notice.
            pub const SOFT: Rgba = Rgba::new(0xff, 0xb3, 0x47, 0x24);
        }
        pub mod bad {
            #[allow(unused_imports)]
            use super::*;
            /// A dot, a bar, a badge fill, an armed destructive button.
            pub const DEFAULT: Rgba = Rgba::rgb(0xff, 0x4d, 0x4d);
            /// Text that says what failed.
            pub const INK: Rgba = Rgba::rgb(0xfe, 0x6c, 0x67);
            /// Text on a bad fill.
            pub const ON: Rgba = Rgba::rgb(0x10, 0x10, 0x12);
            /// The ground of an error notice.
            pub const SOFT: Rgba = Rgba::new(0xff, 0x4d, 0x4d, 0x24);
        }
        pub mod wash {
            #[allow(unused_imports)]
            use super::*;
            /// Under the pointer: a row, a menu item, a quiet button.
            pub const HOVER: Rgba = Rgba::new(0xff, 0xff, 0xff, 0x0f);
            /// Held down: a quiet button or a row while it is pressed. A toggle that stays on is the accent, not this.
            pub const PRESSED: Rgba = Rgba::new(0xff, 0xff, 0xff, 0x1a);
            /// Picked up and being dragged: a row on its way to a new place, with elevation.menu under it. Material's 16%.
            pub const DRAGGED: Rgba = Rgba::new(0xff, 0xff, 0xff, 0x29);
        }
        /// Behind a modal dialog.
        pub const VEIL: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x8c);
    }
    pub mod light {
        #[allow(unused_imports)]
        use super::*;
        pub mod surface {
            #[allow(unused_imports)]
            use super::*;
            /// The app's background: the room everything else is in.
            pub const GROUND: Rgba = Rgba::rgb(0xec, 0xec, 0xef);
            /// A region set on the ground: a sidebar, an inspector, a card.
            pub const PANEL: Rgba = Rgba::rgb(0xf5, 0xf5, 0xf7);
            /// Set into a panel: a field, a track, a well, a list.
            pub const INSET: Rgba = Rgba::rgb(0xe2, 0xe2, 0xe7);
            /// Anything you can press at rest: a button, a key, a chip that does something.
            pub const RAISED: Rgba = Rgba::rgb(0xfb, 0xfb, 0xfc);
            /// A raised control under the pointer.
            pub const RAISED_HOVER: Rgba = Rgba::rgb(0xd6, 0xd6, 0xdc);
            /// Things that float above the page: menus, popovers, dialogs, toasts. Always with a line and an elevation.
            pub const OVERLAY: Rgba = Rgba::rgb(0xff, 0xff, 0xff);
            /// Where the work is shown: the stage, the video, the pixel map. Dark in both themes, because what is shown there is light.
            pub const CANVAS: Rgba = Rgba::rgb(0x10, 0x10, 0x12);
        }
        pub mod ink {
            #[allow(unused_imports)]
            use super::*;
            /// What the screen is about. Passes 4.5:1 on every surface.
            pub const PRIMARY: Rgba = Rgba::rgb(0x1c, 0x1c, 0x1e);
            /// Labels, supporting values, the text on a quiet button. Passes 4.5:1 on every surface.
            pub const SECONDARY: Rgba = Rgba::rgb(0x3c, 0x3c, 0x44);
            /// Hints, units, timestamps, placeholders. Passes 4.5:1 on ground, panel, inset and overlay; not used on a raised control.
            pub const TERTIARY: Rgba = Rgba::rgb(0x5c, 0x5c, 0x66);
            /// Off: a control that cannot be used now, a source that is not sending. Never for content anyone has to read.
            pub const DISABLED: Rgba = Rgba::rgb(0x8c, 0x8c, 0x96);
            /// Text on an inverted chip or tooltip whose fill is ink/primary.
            pub const INVERSE: Rgba = Rgba::rgb(0xf5, 0xf5, 0xf7);
            /// Text laid over the canvas — an overlay on video, a label on the stage. Light in both themes, as the canvas is dark in both.
            pub const ON_CANVAS: Rgba = Rgba::rgb(0xd2, 0xd2, 0xd8);
        }
        pub mod line {
            #[allow(unused_imports)]
            use super::*;
            /// A hairline between regions or rows. Decorative: it carries no meaning on its own.
            pub const SUBTLE: Rgba = Rgba::rgb(0xc4, 0xc4, 0xcc);
            /// A firmer division, and the edge of anything that floats.
            pub const STRONG: Rgba = Rgba::rgb(0x8c, 0x8c, 0x96);
            /// The edge that says 'this is a field' — 3:1 against ground, panel and inset in both themes (WCAG 1.4.11). Separate from line/subtle so a quiet divider can never drag a control below the line.
            pub const CONTROL: Rgba = Rgba::rgb(0x6d, 0x6c, 0x76);
        }
        pub mod accent {
            #[allow(unused_imports)]
            use super::*;
            /// Fill of the primary action; the selection's edge; the focus ring.
            pub const DEFAULT: Rgba = Rgba::rgb(0x03, 0x6a, 0x91);
            /// The primary action under the pointer.
            pub const HOVER: Rgba = Rgba::rgb(0x01, 0x5b, 0x7e);
            /// Text in the accent: a link, the selected tab's label. A step darker than the fill on a light ground, so it still reads on the selection wash.
            pub const INK: Rgba = Rgba::rgb(0x01, 0x5b, 0x7e);
            /// Text and icons on an accent fill.
            pub const ON: Rgba = Rgba::rgb(0xff, 0xff, 0xff);
            /// The selection wash: a selected row, a drop target.
            pub const SOFT: Rgba = Rgba::new(0x03, 0x6a, 0x91, 0x1a);
        }
        /// The keyboard focus ring: 2px, outside the control, on everything operable.
        pub const FOCUS: Rgba = Rgba::rgb(0x03, 0x6a, 0x91);
        pub mod ok {
            #[allow(unused_imports)]
            use super::*;
            /// A dot, a bar, a badge fill.
            pub const DEFAULT: Rgba = Rgba::rgb(0x02, 0x6d, 0x3a);
            /// Text that says it is fine.
            pub const INK: Rgba = Rgba::rgb(0x00, 0x6a, 0x38);
            /// Text on an ok fill.
            pub const ON: Rgba = Rgba::rgb(0xff, 0xff, 0xff);
            /// The ground of an ok notice.
            pub const SOFT: Rgba = Rgba::new(0x02, 0x6d, 0x3a, 0x1a);
        }
        pub mod warn {
            #[allow(unused_imports)]
            use super::*;
            /// A dot, a bar, a badge fill.
            pub const DEFAULT: Rgba = Rgba::rgb(0xb8, 0x79, 0x0b);
            /// Text that asks for attention.
            pub const INK: Rgba = Rgba::rgb(0x80, 0x52, 0x00);
            /// Text on a warn fill — dark in both themes, because amber is a light colour.
            pub const ON: Rgba = Rgba::rgb(0x10, 0x10, 0x12);
            /// The ground of a warning notice.
            pub const SOFT: Rgba = Rgba::new(0xb8, 0x79, 0x0b, 0x29);
        }
        pub mod bad {
            #[allow(unused_imports)]
            use super::*;
            /// A dot, a bar, a badge fill, an armed destructive button.
            pub const DEFAULT: Rgba = Rgba::rgb(0xbe, 0x09, 0x20);
            /// Text that says what failed.
            pub const INK: Rgba = Rgba::rgb(0xbb, 0x01, 0x1e);
            /// Text on a bad fill.
            pub const ON: Rgba = Rgba::rgb(0xff, 0xff, 0xff);
            /// The ground of an error notice.
            pub const SOFT: Rgba = Rgba::new(0xbe, 0x09, 0x20, 0x1a);
        }
        pub mod wash {
            #[allow(unused_imports)]
            use super::*;
            /// Under the pointer: a row, a menu item, a quiet button.
            pub const HOVER: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x0f);
            /// Held down: a quiet button or a row while it is pressed. A toggle that stays on is the accent, not this.
            pub const PRESSED: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x1a);
            /// Picked up and being dragged: a row on its way to a new place, with elevation.menu under it. Material's 16%.
            pub const DRAGGED: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x29);
        }
        /// Behind a modal dialog.
        pub const VEIL: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x66);
    }
}

/// Shadows for what floats, per theme.
pub mod elevation {
    #[allow(unused_imports)]
    use super::*;
    pub mod dark {
        #[allow(unused_imports)]
        use super::*;
        /// Menus, popovers, toasts.
        pub const MENU: Shadow = Shadow { offset_x: 0.0, offset_y: 8.0, blur: 24.0, spread: 0.0, color: Rgba::new(0x00, 0x00, 0x00, 0x73) };
        /// Dialogs.
        pub const MODAL: Shadow = Shadow { offset_x: 0.0, offset_y: 18.0, blur: 50.0, spread: 0.0, color: Rgba::new(0x00, 0x00, 0x00, 0x8c) };
    }
    pub mod light {
        #[allow(unused_imports)]
        use super::*;
        /// Menus, popovers, toasts.
        pub const MENU: Shadow = Shadow { offset_x: 0.0, offset_y: 8.0, blur: 24.0, spread: 0.0, color: Rgba::new(0x00, 0x00, 0x00, 0x33) };
        /// Dialogs.
        pub const MODAL: Shadow = Shadow { offset_x: 0.0, offset_y: 18.0, blur: 50.0, spread: 0.0, color: Rgba::new(0x00, 0x00, 0x00, 0x4d) };
    }
}

/// Font families, most preferred first, and weights.
pub mod font {
    pub const SANS: &[&str] = &["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
    pub const MONO: &[&str] = &["IBM Plex Mono", "ui-monospace", "SF Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"];
    pub const DISPLAY: &[&str] = &["Archivo", "IBM Plex Sans", "system-ui", "sans-serif"];
    pub mod weight {
        pub const REGULAR: u16 = 400;
        pub const MEDIUM: u16 = 500;
        pub const SEMIBOLD: u16 = 600;
        pub const BOLD: u16 = 700;
    }
}

/// Text styles, one module per density.
pub mod text {
    #[allow(unused_imports)]
    use super::*;
    pub mod regular {
        #[allow(unused_imports)]
        use super::*;
        pub const LABEL: TextStyle = TextStyle { family: font::SANS, size: 11.0, weight: 500, leading: 1.2, tracking_em: 0.08, uppercase: true };
        pub const CAPTION: TextStyle = TextStyle { family: font::SANS, size: 12.0, weight: 400, leading: 1.35, tracking_em: 0.0, uppercase: false };
        pub const BODY: TextStyle = TextStyle { family: font::SANS, size: 13.0, weight: 400, leading: 1.45, tracking_em: 0.0, uppercase: false };
        pub const CONTROL: TextStyle = TextStyle { family: font::SANS, size: 13.0, weight: 500, leading: 1.2, tracking_em: 0.0, uppercase: false };
        pub const PROSE: TextStyle = TextStyle { family: font::SANS, size: 14.0, weight: 400, leading: 1.55, tracking_em: 0.0, uppercase: false };
        pub const TITLE: TextStyle = TextStyle { family: font::SANS, size: 15.0, weight: 600, leading: 1.3, tracking_em: 0.0, uppercase: false };
        pub const HEADING: TextStyle = TextStyle { family: font::DISPLAY, size: 20.0, weight: 600, leading: 1.2, tracking_em: 0.0, uppercase: false };
        pub const DISPLAY: TextStyle = TextStyle { family: font::DISPLAY, size: 32.0, weight: 700, leading: 1.1, tracking_em: -0.01, uppercase: false };
        pub const NUMERIC: TextStyle = TextStyle { family: font::MONO, size: 13.0, weight: 400, leading: 1.2, tracking_em: 0.0, uppercase: false };
        pub const READOUT: TextStyle = TextStyle { family: font::MONO, size: 22.0, weight: 500, leading: 1.0, tracking_em: 0.0, uppercase: false };
        pub const CODE: TextStyle = TextStyle { family: font::MONO, size: 13.0, weight: 400, leading: 1.5, tracking_em: 0.0, uppercase: false };
    }
    pub mod compact {
        #[allow(unused_imports)]
        use super::*;
        pub const LABEL: TextStyle = TextStyle { family: font::SANS, size: 11.0, weight: 500, leading: 1.2, tracking_em: 0.08, uppercase: true };
        pub const CAPTION: TextStyle = TextStyle { family: font::SANS, size: 11.0, weight: 400, leading: 1.35, tracking_em: 0.0, uppercase: false };
        pub const BODY: TextStyle = TextStyle { family: font::SANS, size: 12.0, weight: 400, leading: 1.45, tracking_em: 0.0, uppercase: false };
        pub const CONTROL: TextStyle = TextStyle { family: font::SANS, size: 12.0, weight: 500, leading: 1.2, tracking_em: 0.0, uppercase: false };
        pub const PROSE: TextStyle = TextStyle { family: font::SANS, size: 12.0, weight: 400, leading: 1.55, tracking_em: 0.0, uppercase: false };
        pub const TITLE: TextStyle = TextStyle { family: font::SANS, size: 13.0, weight: 600, leading: 1.3, tracking_em: 0.0, uppercase: false };
        pub const HEADING: TextStyle = TextStyle { family: font::DISPLAY, size: 18.0, weight: 600, leading: 1.2, tracking_em: 0.0, uppercase: false };
        pub const DISPLAY: TextStyle = TextStyle { family: font::DISPLAY, size: 28.0, weight: 700, leading: 1.1, tracking_em: -0.01, uppercase: false };
        pub const NUMERIC: TextStyle = TextStyle { family: font::MONO, size: 12.0, weight: 400, leading: 1.2, tracking_em: 0.0, uppercase: false };
        pub const READOUT: TextStyle = TextStyle { family: font::MONO, size: 22.0, weight: 500, leading: 1.0, tracking_em: 0.0, uppercase: false };
        pub const CODE: TextStyle = TextStyle { family: font::MONO, size: 12.0, weight: 400, leading: 1.5, tracking_em: 0.0, uppercase: false };
    }
    pub mod touch {
        #[allow(unused_imports)]
        use super::*;
        pub const LABEL: TextStyle = TextStyle { family: font::SANS, size: 12.0, weight: 500, leading: 1.2, tracking_em: 0.08, uppercase: true };
        pub const CAPTION: TextStyle = TextStyle { family: font::SANS, size: 13.0, weight: 400, leading: 1.35, tracking_em: 0.0, uppercase: false };
        pub const BODY: TextStyle = TextStyle { family: font::SANS, size: 15.0, weight: 400, leading: 1.45, tracking_em: 0.0, uppercase: false };
        pub const CONTROL: TextStyle = TextStyle { family: font::SANS, size: 15.0, weight: 500, leading: 1.2, tracking_em: 0.0, uppercase: false };
        pub const PROSE: TextStyle = TextStyle { family: font::SANS, size: 16.0, weight: 400, leading: 1.55, tracking_em: 0.0, uppercase: false };
        pub const TITLE: TextStyle = TextStyle { family: font::SANS, size: 17.0, weight: 600, leading: 1.3, tracking_em: 0.0, uppercase: false };
        pub const HEADING: TextStyle = TextStyle { family: font::DISPLAY, size: 24.0, weight: 600, leading: 1.2, tracking_em: 0.0, uppercase: false };
        pub const DISPLAY: TextStyle = TextStyle { family: font::DISPLAY, size: 40.0, weight: 700, leading: 1.1, tracking_em: -0.01, uppercase: false };
        pub const NUMERIC: TextStyle = TextStyle { family: font::MONO, size: 15.0, weight: 400, leading: 1.2, tracking_em: 0.0, uppercase: false };
        pub const READOUT: TextStyle = TextStyle { family: font::MONO, size: 28.0, weight: 500, leading: 1.0, tracking_em: 0.0, uppercase: false };
        pub const CODE: TextStyle = TextStyle { family: font::MONO, size: 14.0, weight: 400, leading: 1.5, tracking_em: 0.0, uppercase: false };
    }
}

/// The 4px spacing grid: `STEP_N` is N × 4 logical pixels.
pub mod space {
    pub const STEP_0: f32 = 0.0;
    pub const STEP_1: f32 = 4.0;
    pub const STEP_2: f32 = 8.0;
    pub const STEP_3: f32 = 12.0;
    pub const STEP_4: f32 = 16.0;
    pub const STEP_5: f32 = 20.0;
    pub const STEP_6: f32 = 24.0;
    pub const STEP_8: f32 = 32.0;
    pub const STEP_10: f32 = 40.0;
    pub const STEP_12: f32 = 48.0;
    pub const STEP_16: f32 = 64.0;
    pub const HAIRLINE: f32 = 1.0;
    pub const HALF: f32 = 2.0;
}

/// Control geometry per density, in logical pixels.
pub mod size {
    pub mod regular {
        pub const CONTROL: f32 = 32.0;
        pub const CONTROL_SM: f32 = 24.0;
        pub const CONTROL_PADDING: f32 = 12.0;
        pub const TARGET: f32 = 24.0;
        pub const ICON: f32 = 16.0;
        pub const ROW: f32 = 32.0;
        pub const BAR: f32 = 48.0;
        pub const RAIL: f32 = 72.0;
        pub const RAIL_EXPANDED: f32 = 224.0;
        pub const NAVBAR: f32 = 56.0;
        pub const CRUMB: f32 = 200.0;
        pub const FOCUS_RING: f32 = 2.0;
    }
    pub mod compact {
        pub const CONTROL: f32 = 26.0;
        pub const CONTROL_SM: f32 = 20.0;
        pub const CONTROL_PADDING: f32 = 8.0;
        pub const TARGET: f32 = 24.0;
        pub const ICON: f32 = 14.0;
        pub const ROW: f32 = 24.0;
        pub const BAR: f32 = 40.0;
        pub const RAIL: f32 = 56.0;
        pub const RAIL_EXPANDED: f32 = 200.0;
        pub const NAVBAR: f32 = 48.0;
        pub const CRUMB: f32 = 160.0;
        pub const FOCUS_RING: f32 = 2.0;
    }
    pub mod touch {
        pub const CONTROL: f32 = 44.0;
        pub const CONTROL_SM: f32 = 32.0;
        pub const CONTROL_PADDING: f32 = 16.0;
        pub const TARGET: f32 = 44.0;
        pub const ICON: f32 = 20.0;
        pub const ROW: f32 = 44.0;
        pub const BAR: f32 = 56.0;
        pub const RAIL: f32 = 80.0;
        pub const RAIL_EXPANDED: f32 = 280.0;
        pub const NAVBAR: f32 = 64.0;
        pub const CRUMB: f32 = 160.0;
        pub const FOCUS_RING: f32 = 2.0;
    }
}

/// Corner radii per density, in logical pixels.
pub mod radius {
    pub mod regular {
        pub const NONE: f32 = 0.0;
        pub const CONTROL: f32 = 4.0;
        pub const PANEL: f32 = 6.0;
        pub const OVERLAY: f32 = 8.0;
        pub const PILL: f32 = 999.0;
    }
    pub mod compact {
        pub const NONE: f32 = 0.0;
        pub const CONTROL: f32 = 3.0;
        pub const PANEL: f32 = 4.0;
        pub const OVERLAY: f32 = 6.0;
        pub const PILL: f32 = 999.0;
    }
    pub mod touch {
        pub const NONE: f32 = 0.0;
        pub const CONTROL: f32 = 6.0;
        pub const PANEL: f32 = 8.0;
        pub const OVERLAY: f32 = 12.0;
        pub const PILL: f32 = 999.0;
    }
}

/// Transition durations in milliseconds, at full motion; see [`motion`] for reduced.
pub mod duration {
    pub const INSTANT: u32 = 70;
    pub const FAST: u32 = 120;
    pub const BASE: u32 = 160;
    pub const SLOW: u32 = 240;
}

/// Cubic-bézier control points.
pub mod easing {
    pub const STANDARD: [f32; 4] = [0.2, 0.0, 0.0, 1.0];
    pub const ENTER: [f32; 4] = [0.0, 0.0, 0.2, 1.0];
    pub const EXIT: [f32; 4] = [0.4, 0.0, 1.0, 1.0];
    pub const EMPHASIZED_ENTER: [f32; 4] = [0.05, 0.7, 0.1, 1.0];
    pub const EMPHASIZED_EXIT: [f32; 4] = [0.3, 0.0, 0.8, 0.15];
    pub const LINEAR: [f32; 4] = [0.0, 0.0, 1.0, 1.0];
}

/// Motion per mode: `full`, and `reduced` (no movement; fades at most `fast`).
pub mod motion {
    pub mod full {
        pub mod duration {
            pub const INSTANT: u32 = 70;
            pub const FAST: u32 = 120;
            pub const BASE: u32 = 160;
            pub const SLOW: u32 = 240;
        }
        pub mod offset {
            pub const SMALL: f32 = 4.0;
            pub const MEDIUM: f32 = 8.0;
            pub const LARGE: f32 = 24.0;
        }
        pub mod scale {
            pub const ENTER: f32 = 0.96;
        }
        pub const TRAVEL: f32 = 1.0;
        pub mod cycle {
            pub const SPIN: u32 = 900;
            pub const SWEEP: u32 = 1400;
            pub const PULSE: u32 = 1600;
        }
    }
    pub mod reduced {
        pub mod duration {
            pub const INSTANT: u32 = 70;
            pub const FAST: u32 = 120;
            pub const BASE: u32 = 120;
            pub const SLOW: u32 = 120;
        }
        pub mod offset {
            pub const SMALL: f32 = 0.0;
            pub const MEDIUM: f32 = 0.0;
            pub const LARGE: f32 = 0.0;
        }
        pub mod scale {
            pub const ENTER: f32 = 1.0;
        }
        pub const TRAVEL: f32 = 0.0;
        pub mod cycle {
            pub const SPIN: u32 = 900;
            pub const SWEEP: u32 = 1400;
            pub const PULSE: u32 = 1600;
        }
    }
}

/// Behavioural timers in milliseconds.
pub mod timing {
    pub const HOLD: u32 = 500;
    pub const ARM: u32 = 3000;
    pub const NOTICE: u32 = 4000;
    pub const TOOLTIP: u32 = 500;
}

/// Stacking order.
pub mod layer {
    pub const STICKY: i32 = 10;
    pub const MODAL: i32 = 200;
    pub const POPOVER: i32 = 300;
    pub const TOAST: i32 = 400;
    pub const TOOLTIP: i32 = 500;
}

